version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"  # Mapeia a porta 5432 do contêiner para a porta 5432 do host
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
